version: '3.8'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sigma-bot-app
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    container_name: sigma-bot-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"


volumes:
  db_data: